apiVersion: v1
kind: Deployment
metadata:
  name: container-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-registry
  template:
    metadata:
      labels:
        app: container-registry
    spec:
      containers:
      - name: container-registry
        image: registry:2
        ports:
        - containerPort: 5000
          protocol: TCP
