apiVersion: v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: reg
        image: registry:2
        ports:
        - containerPort: 5000
          protocol: TCP
          hostPort: 5000
          name: registry
        - containerPort: 80
          protocol: TCP
          hostPort: 5080
          name: web
        volumeMounts:
        - name: registry-storage
          mountPath: /var/lib/registry:Z
      volumes:
      - name: registry-storage
        hostPath:
          path: /media/ContainerStorage/registry