apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-db
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-db
  template:
    metadata:
      labels:
        app: registry-db
    spec:
      containers:
        - name: registry-db
          image: mongo:4.4.1
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: registry-db-secrets
                  key: root-password
            - name: MONGO_INITDB_DATABASE
              value: registry
          ports:
            - name: mongodb
              containerPort: 27017
          volumeMounts:
            - name: registry-db-pv
              mountPath: /data/db
      volumes:
        - name: registry-db-pv
          persistentVolumeClaim:
            claimName: registry-db-pvc
