#!/usr/bin/env bash
# NOTE: This file is automatically generated!
# TODO: currently this needs to be run from the project directory
CHART_SELECTOR=traefik
CHART_NAME=traefik
CHART_URL=https://traefik.github.io/charts
INSTANCE_NAME=traefik
cd ..
./scripts/get_helm.sh \
  ${CHART_SELECTOR} \
  ${CHART_NAME} \
  ${CHART_URL} \
  ${INSTANCE_NAME}
