#!/usr/bin/env bash
# NOTE: This file is automatically generated!
# TODO: Currently needs to be run from the k3s dir
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd ${SCRIPT_DIR}
kubectl apply -k traefik
